<?php

$kurose_chapters = [
    ["book_id" => 1, "group_id" => 1, "name" => "1.1 What Is the Internet?", "page" => 2],
    ["book_id" => 1, "group_id" => 1, "name" => "1.2 The Network Edge", "page" => 9],
    ["book_id" => 1, "group_id" => 1, "name" => "1.3 The Network Core", "page" => 21],
    ["book_id" => 1, "group_id" => 1, "name" => "1.4 Delay, Loss, and Throughput in Packet-Switched Networks", "page" => 35],
    ["book_id" => 1, "group_id" => 1, "name" => "1.5 Protocol Layers and Their Service Models", "page" => 47],
    ["book_id" => 1, "group_id" => 1, "name" => "1.6 Networks Under Attack", "page" => 55],
    ["book_id" => 1, "group_id" => 1, "name" => "1.7 History of Computer Networking and the Internet", "page" => 59],
    ["book_id" => 1, "group_id" => 1, "name" => "1.8 Summary", "page" => 65],
    ["book_id" => 1, "group_id" => 2, "name" => "2.1 Principles of Network Applications", "page" => 84], 
    ["book_id" => 1, "group_id" => 2, "name" => "2.2 The Web and HTTP", "page" => 98], 
    ["book_id" => 1, "group_id" => 2, "name" => "2.3 Electronic Mail in the Internet", "page" => 116], 
    ["book_id" => 1, "group_id" => 2, "name" => "2.4 DNS—The Internet’s Directory Service", "page" => 126], 
    ["book_id" => 1, "group_id" => 2, "name" => "2.5 Peer-to-Peer Applications", "page" => 140], 
    ["book_id" => 1, "group_id" => 2, "name" => "2.8 Summary", "page" => 170], 
    ["book_id" => 1, "group_id" => 3, "name" => "3.1 Introduction and Transport-Layer Services", "page" => 188], 
    ["book_id" => 1, "group_id" => 3, "name" => "3.2 Multiplexing and Demultiplexing", "page" => 193], 
    ["book_id" => 1, "group_id" => 3, "name" => "3.3 Connectionless Transport: UDP", "page" => 200], 
    ["book_id" => 1, "group_id" => 3, "name" => "3.4 Principles of Reliable Data Transfer", "page" => 206], 
    ["book_id" => 1, "group_id" => 3, "name" => "3.5 Connection-Oriented Transport: TCP", "page" => 233], 
    ["book_id" => 1, "group_id" => 3, "name" => "3.6 Principles of Congestion Control", "page" => 261],
    ["book_id" => 1, "group_id" => 3, "name" => "3.7 TCP Congestion Control", "page" => 269], 
    ["book_id" => 1, "group_id" => 3, "name" => "3.8 Summary", "page" => 284], 
    ["book_id" => 1, "group_id" => 4, "name" => "4.1 Overview of Network Layer", "page" => 306], 
    ["book_id" => 1, "group_id" => 4, "name" => "4.2 What’s Inside a Router?", "page" => 313], 
    ["book_id" => 1, "group_id" => 4, "name" => "4.3 The Internet Protocol (IP): IPv4, Addressing, IPv6, and More", "page" => 329], 
    ["book_id" => 1, "group_id" => 4, "name" => "4.4 Generalized Forwarding and SDN", "page" => 354], 
    ["book_id" => 1, "group_id" => 4, "name" => "4.5 Summary", "page" => 361],
    ["book_id" => 1, "group_id" => 5, "name" => "5.1 Introduction", "page" => 374], 
    ["book_id" => 1, "group_id" => 5, "name" => "5.2 Routing Algorithms", "page" => 376], 
    ["book_id" => 1, "group_id" => 5, "name" => "5.3 Intra-AS Routing in the Internet: OSPF", "page" => 391], 
    ["book_id" => 1, "group_id" => 5, "name" => "5.4 Routing Among the ISPs: BGP", "page" => 395], 
    ["book_id" => 1, "group_id" => 5, "name" => "5.5 The SDN Control Plane", "page" => 407], 
    ["book_id" => 1, "group_id" => 5, "name" => "5.6 ICMP: The Internet Control Message Protocol", "page" => 419], 
    ["book_id" => 1, "group_id" => 5, "name" => "5.7 Network Management and SNMP", "page" => 421], 
    ["book_id" => 1, "group_id" => 5, "name" => "5.8 Summary", "page" => 426], 
    ["book_id" => 1, "group_id" => 6, "name" => "6.1 Introduction to the Link Layer", "page" => 440], 
    ["book_id" => 1, "group_id" => 6, "name" => "6.2 Error-Detection and -Correction Techniques", "page" => 444], 
    ["book_id" => 1, "group_id" => 6, "name" => "6.3 Multiple Access Links and Protocols", "page" => 451], 
    ["book_id" => 1, "group_id" => 6, "name" => "6.4 Switched Local Area Networks", "page" => 467], 
    ["book_id" => 1, "group_id" => 6, "name" => "6.5 Link Virtualization: A Network as a Link Layer", "page" => 491], 
    ["book_id" => 1, "group_id" => 6, "name" => "6.6 Data Center Networking", "page" => 495], 
    ["book_id" => 1, "group_id" => 6, "name" => "6.8 Summary", "page" => 506], 
    ["book_id" => 1, "group_id" => 7, "name" => "7.1 Introduction", "page" => 520], 
    ["book_id" => 1, "group_id" => 7, "name" => "7.2 Wireless Links and Network Characteristics", "page" => 525], 
    ["book_id" => 1, "group_id" => 7, "name" => "7.3 WiFi: 802.11 Wireless LANs", "page" => 532], 
    ["book_id" => 1, "group_id" => 7, "name" => "7.4 Cellular Internet Access", "page" => 551], 
    ["book_id" => 1, "group_id" => 7, "name" => "7.5 Mobility Management: Principles", "page" => 560], 
    ["book_id" => 1, "group_id" => 7, "name" => "7.6 Mobile IP", "page" => 570], 
    ["book_id" => 1, "group_id" => 7, "name" => "7.7 Managing Mobility in Cellular Networks", "page" => 574], 
    ["book_id" => 1, "group_id" => 7, "name" => "7.8 Wireless and Mobility: Impact on Higher-Layer Protocols", "page" => 580], 
    ["book_id" => 1, "group_id" => 7, "name" => "7.9 Summary", "page" => 582], 
    ["book_id" => 1, "group_id" => 8, "name" => "8.1 What Is Network Security?", "page" => 594], 
    ["book_id" => 1, "group_id" => 8, "name" => "8.2 Principles of Cryptography", "page" => 596], 
    ["book_id" => 1, "group_id" => 8, "name" => "8.3 Message Integrity and Digital Signatures", "page" => 610], 
    ["book_id" => 1, "group_id" => 8, "name" => "8.4 End-Point Authentication", "page" => 621], 
    ["book_id" => 1, "group_id" => 8, "name" => "8.5 Securing E-Mail", "page" => 626], 
    ["book_id" => 1, "group_id" => 8, "name" => "8.6 Securing TCP Connections: SSL", "page" => 631], 
    ["book_id" => 1, "group_id" => 8, "name" => "8.8 Securing Wireless LANs", "page" => 646], 
    ["book_id" => 1, "group_id" => 8, "name" => "8.10 Summary", "page" => 662], 
    ["book_id" => 1, "group_id" => 9, "name" => "9.1 Multimedia Networking Applications", "page" => 676], 
    ["book_id" => 1, "group_id" => 9, "name" => "9.2 Streaming Stored Video", "page" => 681], 
    ["book_id" => 1, "group_id" => 9, "name" => "9.3 Voice-over-IP", "page" => 688], 
    ["book_id" => 1, "group_id" => 9, "name" => "9.4 Protocols for Real-Time Conversational Applications", "page" => 700], 
    ["book_id" => 1, "group_id" => 9, "name" => "9.5 Network Support for Multimedia", "page" => 709], 
    ["book_id" => 1, "group_id" => 9, "name" => "9.6 Summary", "page" => 726], 
];