<?php

$tanenbaum_chapters = [
    ["book_id" => 2, "group_id" => 1, "name" => "1.1 What Is An Operating System?", "page" => 3],
    ["book_id" => 2, "group_id" => 1, "name" => "1.2 History Of Operating Systems", "page" => 7],
    ["book_id" => 2, "group_id" => 1, "name" => "1.3 Computer Hardware Review", "page" => 17],
    ["book_id" => 2, "group_id" => 1, "name" => "1.4 The Operating System Zoo", "page" => 31],
    ["book_id" => 2, "group_id" => 1, "name" => "1.5 Operating System Concepts", "page" => 35],
    ["book_id" => 2, "group_id" => 1, "name" => "1.6 System Calls", "page" => 47],
    ["book_id" => 2, "group_id" => 1, "name" => "1.7 Operating System Structure", "page" => 60],
    ["book_id" => 2, "group_id" => 1, "name" => "1.8 The World According To C", "page" => 70],
    ["book_id" => 2, "group_id" => 1, "name" => "1.9 Research On Operating Systems", "page" => 74],
    ["book_id" => 2, "group_id" => 1, "name" => "1.10 Outline Of The Rest Of This Book", "page" => 75],
    ["book_id" => 2, "group_id" => 1, "name" => "1.11 Metric Units", "page" => 76],
    ["book_id" => 2, "group_id" => 1, "name" => "1.12 Summary", "page" => 77],
    ["book_id" => 2, "group_id" => 2, "name" => "2.1 Processes", "page" => 81],
    ["book_id" => 2, "group_id" => 2, "name" => "2.2 Threads", "page" => 93],
    ["book_id" => 2, "group_id" => 2, "name" => "2.3 Interprocess Communication", "page" => 115],
    ["book_id" => 2, "group_id" => 2, "name" => "2.4 Scheduling", "page" => 143],
    ["book_id" => 2, "group_id" => 2, "name" => "2.5 Classical Ipc Problems", "page" => 161],
    ["book_id" => 2, "group_id" => 2, "name" => "2.6 Research On Processes And Threads", "page" => 166],
    ["book_id" => 2, "group_id" => 2, "name" => "2.7 Summary", "page" => 167],
    ["book_id" => 2, "group_id" => 3, "name" => "3.1 No Memory Abstraction", "page" => 174],
    ["book_id" => 2, "group_id" => 3, "name" => "3.2 A Memory Abstraction: Address Spaces", "page" => 177],
    ["book_id" => 2, "group_id" => 3, "name" => "3.3 Virtual Memory", "page" => 186],
    ["book_id" => 2, "group_id" => 3, "name" => "3.4 Page Replacement Algorithms", "page" => 199],
    ["book_id" => 2, "group_id" => 3, "name" => "3.5 Design Issues For Paging Systems", "page" => 214],
    ["book_id" => 2, "group_id" => 3, "name" => "3.6 Implementation Issues", "page" => 225],
    ["book_id" => 2, "group_id" => 3, "name" => "3.7 Segmentation", "page" => 232],
    ["book_id" => 2, "group_id" => 3, "name" => "3.8 Research On Memory Management", "page" => 245],
    ["book_id" => 2, "group_id" => 3, "name" => "3.9 Summary", "page" => 246] ,
    ["book_id" => 2, "group_id" => 4, "name" => "4.1 Files", "page" => 255],
    ["book_id" => 2, "group_id" => 4, "name" => "4.2 Directories", "page" => 266],
    ["book_id" => 2, "group_id" => 4, "name" => "4.3 File System Implementation", "page" => 271],
    ["book_id" => 2, "group_id" => 4, "name" => "4.4 File System Management And Optimization", "page" => 290],
    ["book_id" => 2, "group_id" => 4, "name" => "4.5 Example File Systems", "page" => 310],
    ["book_id" => 2, "group_id" => 4, "name" => "4.6 Research On File Systems", "page" => 322],
    ["book_id" => 2, "group_id" => 4, "name" => "4.7 Summary", "page" => 322] ,
    ["book_id" => 2, "group_id" => 5, "name" => "5.1 Principles Of I/O Hardware", "page" => 327],
    ["book_id" => 2, "group_id" => 5, "name" => "5.2 Principles Of I/O Software", "page" => 341],
    ["book_id" => 2, "group_id" => 5, "name" => "5.3 I/0 Software Layers", "page" => 346],
    ["book_id" => 2, "group_id" => 5, "name" => "5.4 Disks", "page" => 358],
    ["book_id" => 2, "group_id" => 5, "name" => "5.5 Clocks", "page" => 386],
    ["book_id" => 2, "group_id" => 5, "name" => "5.6 User Interfaces: Keyboard, Mouse, Monitor", "page" => 392],
    ["book_id" => 2, "group_id" => 5, "name" => "5.7 Thin Clients", "page" => 413],
    ["book_id" => 2, "group_id" => 5, "name" => "5.8 Power Management", "page" => 415],
    ["book_id" => 2, "group_id" => 5, "name" => "5.9 Research On Input/Output", "page" => 423],
    ["book_id" => 2, "group_id" => 5, "name" => "5.10 Summary", "page" => 424] ,
    ["book_id" => 2, "group_id" => 6, "name" => "6.1 Resources", "page" => 432],
    ["book_id" => 2, "group_id" => 6, "name" => "6.2 Introduction To Deadlocks", "page" => 435],
    ["book_id" => 2, "group_id" => 6, "name" => "6.3 The Ostrich Algorithm", "page" => 439],
    ["book_id" => 2, "group_id" => 6, "name" => "6.4 Deadlock Detection And Recovery", "page" => 440],
    ["book_id" => 2, "group_id" => 6, "name" => "6.5 Deadlock Avoidance", "page" => 446],
    ["book_id" => 2, "group_id" => 6, "name" => "6.6 Deadlock Prevention", "page" => 452],
    ["book_id" => 2, "group_id" => 6, "name" => "6.7 Other Issues", "page" => 455],
    ["book_id" => 2, "group_id" => 6, "name" => "6.8 Research On Deadlocks", "page" => 459],
    ["book_id" => 2, "group_id" => 6, "name" => "6.9 Summary", "page" => 460] ,
    ["book_id" => 2, "group_id" => 7, "name" => "7.1 Introduction To Multimedia", "page" => 466],
    ["book_id" => 2, "group_id" => 7, "name" => "7.2 Multimedia Files", "page" => 470],
    ["book_id" => 2, "group_id" => 7, "name" => "7.3 Video Compression", "page" => 476],
    ["book_id" => 2, "group_id" => 7, "name" => "7.4 Audio Compression", "page" => 482],
    ["book_id" => 2, "group_id" => 7, "name" => "7.5 Multimedia Process Scheduling", "page" => 485],
    ["book_id" => 2, "group_id" => 7, "name" => "7.6 Multimedia File System Paradigms", "page" => 491],
    ["book_id" => 2, "group_id" => 7, "name" => "7.7 File Placement", "page" => 497],
    ["book_id" => 2, "group_id" => 7, "name" => "7.8 Caching", "page" => 508],
    ["book_id" => 2, "group_id" => 7, "name" => "7.9 Disk Scheduling For Multimedia", "page" => 511],
    ["book_id" => 2, "group_id" => 7, "name" => "7.10 Research On Multimedia", "page" => 514],
    ["book_id" => 2, "group_id" => 7, "name" => "7.11 Summary", "page" => 515] ,
    ["book_id" => 2, "group_id" => 8, "name" => "8.1 Multiprocessors", "page" => 524],
    ["book_id" => 2, "group_id" => 8, "name" => "8.2 Multicomputers", "page" => 546],
    ["book_id" => 2, "group_id" => 8, "name" => "8.3 Virtualization", "page" => 566],
    ["book_id" => 2, "group_id" => 8, "name" => "8.4 Distributed Systems", "page" => 578],
    ["book_id" => 2, "group_id" => 8, "name" => "8.5 Research On Multiple Processor Systems", "page" => 602],
    ["book_id" => 2, "group_id" => 8, "name" => "8.6 Summary", "page" => 603] ,
    ["book_id" => 2, "group_id" => 9, "name" => "9.1 The Security Environment", "page" => 611],
    ["book_id" => 2, "group_id" => 9, "name" => "9.2 Basics Of Cryptography", "page" => 614],
    ["book_id" => 2, "group_id" => 9, "name" => "9.3 Protection Mechanisms", "page" => 620],
    ["book_id" => 2, "group_id" => 9, "name" => "9.4 Authentication", "page" => 639],
    ["book_id" => 2, "group_id" => 9, "name" => "9.5 Insider Attacks", "page" => 654],
    ["book_id" => 2, "group_id" => 9, "name" => "9.6 Exploiting Code Bugs", "page" => 657],
    ["book_id" => 2, "group_id" => 9, "name" => "9.7 Malware", "page" => 665],
    ["book_id" => 2, "group_id" => 9, "name" => "9.8 Defenses", "page" => 690],
    ["book_id" => 2, "group_id" => 9, "name" => "9.9 Research On Security", "page" => 709],
    ["book_id" => 2, "group_id" => 9, "name" => "9.10 Summary", "page" => 710] ,
    ["book_id" => 2, "group_id" => 10, "name" => "10.1 History Of Unix And Linux", "page" => 716],
    ["book_id" => 2, "group_id" => 10, "name" => "10.2 Overview Of Linux", "page" => 724],
    ["book_id" => 2, "group_id" => 10, "name" => "10.3 Processes In Linux", "page" => 735],
    ["book_id" => 2, "group_id" => 10, "name" => "10.4 Memory Management In Linux", "page" => 754],
    ["book_id" => 2, "group_id" => 10, "name" => "10.5 Input/Output In Linux", "page" => 767],
    ["book_id" => 2, "group_id" => 10, "name" => "10.6 The Linux File System", "page" => 775],
    ["book_id" => 2, "group_id" => 10, "name" => "10.7 Security In Linux", "page" => 799],
    ["book_id" => 2, "group_id" => 10, "name" => "10.8 Summary", "page" => 802] ,
    ["book_id" => 2, "group_id" => 11, "name" => "11.1 History Of Windows Vista", "page" => 809],
    ["book_id" => 2, "group_id" => 11, "name" => "11.2 Programming Windows Vista", "page" => 815],
    ["book_id" => 2, "group_id" => 11, "name" => "11.3 System Structure", "page" => 827],
    ["book_id" => 2, "group_id" => 11, "name" => "11.4 Processes And Threads In Windows Vista", "page" => 857],
    ["book_id" => 2, "group_id" => 11, "name" => "11.5 Memory Management", "page" => 875],
    ["book_id" => 2, "group_id" => 11, "name" => "11.6 Caching In Windows Vista", "page" => 890],
    ["book_id" => 2, "group_id" => 11, "name" => "11.7 Input/Output In Windows Vista", "page" => 892],
    ["book_id" => 2, "group_id" => 11, "name" => "11.8 The Windows Nt File System", "page" => 902],
    ["book_id" => 2, "group_id" => 11, "name" => "11.9 Security In Windows Vista", "page" => 914],
    ["book_id" => 2, "group_id" => 11, "name" => "11.10 Summary", "page" => 920],
    ["book_id" => 2, "group_id" => 12, "name" => "12.1 The History Of Symbian Os", "page" => 926],
    ["book_id" => 2, "group_id" => 12, "name" => "12.2 An Overview Of Symbian Os", "page" => 928],
    ["book_id" => 2, "group_id" => 12, "name" => "12.3 Processes And Threads In Symbian Os", "page" => 933],
    ["book_id" => 2, "group_id" => 12, "name" => "12.4 Memory Management", "page" => 937],
    ["book_id" => 2, "group_id" => 12, "name" => "12.5 Input And Output", "page" => 941],
    ["book_id" => 2, "group_id" => 12, "name" => "12.6 Storage Systems", "page" => 944],
    ["book_id" => 2, "group_id" => 12, "name" => "12.7 Security In Symbian Os", "page" => 946] ,
    ["book_id" => 2, "group_id" => 12, "name" => "12.8 Communication In Symbian Os", "page" => 949],
    ["book_id" => 2, "group_id" => 12, "name" => "12.9 Summary", "page" => 953] ,
    ["book_id" => 2, "group_id" => 13, "name" => "13.1 The Nature Of The Design Problem", "page" => 956],
    ["book_id" => 2, "group_id" => 13, "name" => "13.2 Interface Design", "page" => 959],
    ["book_id" => 2, "group_id" => 13, "name" => "13.3 Implementation", "page" => 967],
    ["book_id" => 2, "group_id" => 13, "name" => "13.4 Performance", "page" => 983],
    ["book_id" => 2, "group_id" => 13, "name" => "13.5 Project Management", "page" => 990],
    ["book_id" => 2, "group_id" => 13, "name" => "13.6 Trends In Operating System Design", "page" => 994],
    ["book_id" => 2, "group_id" => 13, "name" => "13.7 Summary", "page" => 999] ,
    ["book_id" => 2, "group_id" => 14, "name" => "14.1 Suggestions For Further Reading", "page" => 1003],
    ["book_id" => 2, "group_id" => 14, "name" => "14.2 Alphabetical Bibliography", "page" => 1012] ,
];